name: Setup Java JDK

run-name: ${{github.actor}} learning actions

on: [push]

jobs:

  checks-and-install-node:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4.2.1
      with: 
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
        cache-dependency-path: 'sub-project/pom.xml' # optional
    - name: Build with Maven
      run: mvn -B package --file pom.xml

      
